apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fullstack-app

data:
  POSTGRES_DB: fullstack_db
  POSTGRES_USER: vasile_admin
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  DATABASE_URL: postgresql://vasile_admin:supersecurepassword123@postgres-service:5432/fullstack_db