nameOverride: ""
fullnameOverride: ""

image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 250Mi

persistence:
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi