apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  # Formulating the database hostname directly using the database subchart naming conventions
  DB_HOST: {{ printf "%s-database" .Release.Name | trunc 63 | trimSuffix "-" }}
  DB_PORT: "5432"