FROM python:3.12-alpine AS builder

WORKDIR /app

COPY app/requirements.txt .

RUN pip install --prefix=/install -r requirements.txt

COPY app .

FROM gcr.io/distroless/python3

WORKDIR /app

COPY --from=builder /install /usr/local
COPY --from=builder /app /app

EXPOSE 5000

CMD ["app.py"]