apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment2-config
data:
  DB_USER: "user"
  # DB_PASSWORD: "password"
  DB_NAME: "mydb"
  DB_URL: "jdbc:mysql://host.docker.internal:3306/mydb"
  HOST_SERVER: "host.docker.internal"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment2-file-config
data:
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    