---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spin-credentials
spec:
  secretStoreRef:
    name: intenship/spin
    kind: AWSSecretsManager
  target:
    name: spin-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secret/data/db-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: secret/data/db-credentials
      property: password