apiVersion: v1
kind: Secret
metadata:
  name: deployment2-secret
  # annotations:
  #   kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: deployment2-file-secret
type: Opaque
data:
  user-interface.secrets: ZW5lbXkudHlwZXM9YWxpZW5zLG1vbnN0ZXJzCnBsYXllci5tYXhpbXVtLWxpdmVzPTUgICAg